DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: DELETE http://testserver/delete_user/25 "HTTP/1.1 200 OK"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: POST http://testserver/register_user "HTTP/1.1 200 OK"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: POST http://testserver/register_user "HTTP/1.1 422 Unprocessable Entity"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: GET http://testserver/sum/?a=5&b=10 "HTTP/1.1 200 OK"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: GET http://testserver/sum/?a=-8&b=-3 "HTTP/1.1 200 OK"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: GET http://testserver/sum/?a=0&b=7 "HTTP/1.1 200 OK"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: POST http://testserver/login_user/?username=Negan&password=negan123 "HTTP/1.1 307 Temporary Redirect"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: POST http://testserver/login_user?username=Negan&password=negan123 "HTTP/1.1 200 OK"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: POST http://testserver/login_user/?username=Rick&password=negan "HTTP/1.1 307 Temporary Redirect"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: POST http://testserver/login_user?username=Rick&password=negan "HTTP/1.1 400 Bad Request"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: GET http://testserver/find_user/12 "HTTP/1.1 200 OK"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: GET http://testserver/find_user/1 "HTTP/1.1 404 Not Found"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: POST http://testserver/create_ToDo "HTTP/1.1 200 OK"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: POST http://testserver/create_ToDo "HTTP/1.1 422 Unprocessable Entity"
DEBUG    asyncio:proactor_events.py:626 Using proactor: IocpProactor
INFO     httpx:_client.py:1013 HTTP Request: GET http://testserver/Fetch_data_from_API "HTTP/1.1 200 OK"
